name: BlockBroadcaster
main: net.creepland.blockbroadcaster.BlockBroadcaster
version: ${pom.version}
author: Pabszito
api-version: 1.16

commands:
  blockbroadcaster:
    description: BlockBroadcaster main command.
    aliases: [blockbc]